name: Auto Update Project Info

on:
  push:
    paths:
      - 'data/**'
      - 'README.md'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run update_version script
        run: |
          python scripts/update_version.py

      - name: Inject version and date into README
        run: |
          python scripts/inject_version_into_readme.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md data/project-info.json
          git commit -m "Update version and date in README" || echo "No changes to commit"
          git push
